// countryToIsoCodeMap.ts
export const countryToIsoCodeMap: { [key: string]: string } = {
  "United Kingdom": "GB", // Note: UK uses GB for ISO 3166-1 alpha-2
  "Monaco": "MC",
  "Mauritius": "MU",
  "Equatorial Guinea": "GQ",
  "Eswatini (Swaziland)": "SZ",
  "Fiji": "FJ",
  "Panama": "PA",
  "Chile": "CL",
  "China": "CN",
  "Vietnam": "VN",
  "Guinea": "GN",
  "Norway (Bouvet Island, Peter I Island)": "NO", // Use main country code
  "Poland": "PL",
  "Mexico": "MX",
  "Philippines": "PH",
  "Azerbaijan": "AZ",
  "Georgia": "GE",
  "Venezuela": "VE",
  "Montenegro": "ME",
  "Sri Lanka": "LK",
  "Peru": "PE",
  "United Nations (Non-geographical)": "UN", // Special code, may not have a flag
  "Haiti": "HT",
  "Timor-Leste": "TL",
  "Israel": "IL",
  "Libya": "LY",
  "Cyprus": "CY",
  "Morocco": "MA",
  "Tanzania": "TZ",
  "Colombia": "CO",
  "Liberia": "LR",
  "Nigeria": "NG",
  "Denmark": "DK",
  "Madagascar": "MG",
  "Mauritania": "MR",
  "Niger": "NE",
  "Togo": "TG",
  "Samoa": "WS",
  "Uganda": "UG",
  "Kenya": "KE",
  "Egypt": "EG",
  "Syria": "SY",
  "Somalia": "SO",
  "Pakistan": "PK",
  "Sudan": "SD",
  "Senegal": "SN",
  "Jamaica": "JM",
  "Yemen": "YE",
  "Lesotho": "LS",
  "Malawi": "MW",
  "Algeria": "DZ",
  "Sweden": "SE",
  "Saudi Arabia": "SA",
  "Indonesia": "ID",
  "Japan": "JP",
  "Mongolia": "MN",
  "Jordan": "JO",
  "United States of America": "US",
  "Argentina": "AR",
  "Botswana": "BW",
  "Tonga": "TO",
  "Oman": "OM",
  "Bhutan": "BT",
  "United Arab Emirates": "AE",
  "Qatar": "QA",
  "Bahrain": "BH",
  "Australia": "AU",
  "Nauru": "NR",
  "Andorra": "AD",
  "Gambia": "GM",
  "Bahamas": "BS",
  "Mozambique": "MZ",
  "Cuba": "CU",
  "Bolivia": "BO",
  "Portugal": "PT",
  "Uruguay": "UY",
  "Canada": "CA",
  "Angola": "AO",
  "Cape Verde": "CV",
  "Comoros": "KM",
  "South Korea": "KR",
  "Germany": "DE",
  "Eritrea": "ER",
  "Palestinian Authority": "PS",
  "New Zealand (Cook Islands)": "CK",
  "New Zealand (Niue)": "NU",
  "Bosnia and Herzegovina": "BA",
  "Ireland": "IE",
  "Armenia": "AM",
  "Ukraine": "UA",
  "Iran": "IR",
  "Moldova": "MD",
  "Estonia": "EE",
  "Ethiopia": "ET",
  "Belarus": "BY",
  "Kyrgyz Republic": "KG",
  "Tajikistan": "TJ",
  "Turkmenistan": "TM",
  "France": "FR",
  "Hungary": "HU",
  "Switzerland": "CH",
  "Ecuador": "EC",
  "Dominican Republic": "DO",
  "Honduras": "HN",
  "Iceland": "IS",
  "Italy": "IT",
  "Djibouti": "DJ",
  "Grenada": "GD",
  "Greece": "GR",
  "Guinea-Bissau": "GW",
  "Saint Lucia": "LC",
  "Dominica": "DM",
  "Saint Vincent and the Grenadines": "VC",
  "Luxembourg": "LU",
  "Lithuania": "LT",
  "Bulgaria": "BG",
  "Netherlands": "NL",
  "Netherlands Antilles": "AN", // Historical, consider splitting if specific islands are needed
  "Papua New Guinea": "PG",
  "Aruba": "AW",
  "North Korea": "KP",
  "Brazil": "BR",
  "Suriname": "SR",
  "Russian Federation": "RU",
  "Bangladesh": "BD",
  "Slovenia": "SI",
  "Seychelles": "SC",
  "South Africa": "ZA",
  "Sao Tome and Principe": "ST",
  "Tuvalu": "TV",
  "Kiribati": "KI",
  "Afghanistan": "AF",
  "San Marino": "SM",
  "Palau": "PW",
  "Turkey": "TR",
  "Guatemala": "GT",
  "Costa Rica": "CR",
  "Cameroon": "CM",
  "Central African Republic": "CF",
  "Congo (Republic of the)": "CG",
  "Gabon": "GA",
  "Chad": "TD",
  "Benin": "BJ",
  "Mali": "ML",
  "Uzbekistan": "UZ",
  "Kazakhstan": "KZ",
  "Albania": "AL",
  "Paraguay": "PY",
  "Zimbabwe": "ZW",
  "North Macedonia": "MK",
  "Croatia": "HR",
  "Ghana": "GH",
  "Malta": "MT",
  "Zambia": "ZM",
  "Kuwait": "KW",
  "Sierra Leone": "SL",
  "Trinidad and Tobago": "TT",
  "Myanmar": "MM",
  "Vanuatu": "VU",
  "Latvia": "LV",
  "Romania": "RO",
  "Spain": "ES"
};