export const callsignPrefixesData = [
  { "prefix": "2A", "country": "United Kingdom" },
  { "prefix": "3A", "country": "Monaco" },
  { "prefix": "3B", "country": "Mauritius" },
  { "prefix": "3C", "country": "Equatorial Guinea" },
  { "prefix": "3D6", "country": "Eswatini (Swaziland)" },
  { "prefix": "3D2", "country": "Fiji" },
  { "prefix": "3E", "country": "Panama" },
  { "prefix": "3F", "country": "Panama" }, // Panama has multiple blocks
  { "prefix": "3G", "country": "Chile" },
  { "prefix": "3H", "country": "China" },
  { "prefix": "3I", "country": "China" },
  { "prefix": "3J", "country": "China" },
  { "prefix": "3K", "country": "China" },
  { "prefix": "3L", "country": "China" },
  { "prefix": "3M", "country": "China" },
  { "prefix": "3N", "country": "China" },
  { "prefix": "3O", "country": "China" },
  { "prefix": "3P", "country": "China" },
  { "prefix": "3Q", "country": "China" },
  { "prefix": "3R", "country": "China" },
  { "prefix": "3S", "country": "China" },
  { "prefix": "3T", "country": "China" },
  { "prefix": "3U", "country": "China" },
  { "prefix": "3V", "country": "Tunisia" },
  { "prefix": "3W", "country": "Vietnam" },
  { "prefix": "3X", "country": "Guinea" },
  { "prefix": "3Y", "country": "Norway (Bouvet Island, Peter I Island)" },
  { "prefix": "3Z", "country": "Poland" },
  { "prefix": "4A", "country": "Mexico" },
  { "prefix": "4B", "country": "Mexico" },
  { "prefix": "4C", "country": "Mexico" },
  { "prefix": "4D", "country": "Philippines" },
  { "prefix": "4E", "country": "Philippines" },
  { "prefix": "4F", "country": "Philippines" },
  { "prefix": "4G", "country": "Philippines" },
  { "prefix": "4H", "country": "Philippines" },
  { "prefix": "4I", "country": "Philippines" },
  { "prefix": "4J", "country": "Azerbaijan" },
  { "prefix": "4K", "country": "Azerbaijan" },
  { "prefix": "4L", "country": "Georgia" },
  { "prefix": "4M", "country": "Venezuela" },
  { "prefix": "4O", "country": "Montenegro" },
  { "prefix": "4P", "country": "Sri Lanka" },
  { "prefix": "4Q", "country": "Sri Lanka" },
  { "prefix": "4R", "country": "Sri Lanka" },
  { "prefix": "4S", "country": "Sri Lanka" },
  { "prefix": "4T", "country": "Peru" },
  { "prefix": "4U", "country": "United Nations (Non-geographical)" },
  { "prefix": "4V", "country": "Haiti" },
  { "prefix": "4W", "country": "Timor-Leste" },
  { "prefix": "4X", "country": "Israel" },
  { "prefix": "4Z", "country": "Israel" },
  { "prefix": "5A", "country": "Libya" },
  { "prefix": "5B", "country": "Cyprus" },
  { "prefix": "5C", "country": "Morocco" },
  { "prefix": "5D", "country": "Morocco" },
  { "prefix": "5E", "country": "Morocco" },
  { "prefix": "5F", "country": "Morocco" },
  { "prefix": "5G", "country": "Morocco" },
  { "prefix": "5H", "country": "Tanzania" },
  { "prefix": "5I", "country": "Tanzania" },
  { "prefix": "5J", "country": "Colombia" },
  { "prefix": "5K", "country": "Colombia" },
  { "prefix": "5L", "country": "Liberia" },
  { "prefix": "5M", "country": "Liberia" },
  { "prefix": "5N", "country": "Nigeria" },
  { "prefix": "5O", "country": "Nigeria" },
  { "prefix": "5P", "country": "Denmark" },
  { "prefix": "5Q", "country": "Denmark" },
  { "prefix": "5R", "country": "Madagascar" },
  { "prefix": "5S", "country": "Madagascar" },
  { "prefix": "5T", "country": "Mauritania" },
  { "prefix": "5U", "country": "Niger" },
  { "prefix": "5V", "country": "Togo" },
  { "prefix": "5W", "country": "Samoa" },
  { "prefix": "5X", "country": "Uganda" },
  { "prefix": "5Y", "country": "Kenya" },
  { "prefix": "5Z", "country": "Kenya" },
  { "prefix": "6A", "country": "Egypt" },
  { "prefix": "6B", "country": "Egypt" },
  { "prefix": "6C", "country": "Syria" },
  { "prefix": "6D", "country": "Mexico" },
  { "prefix": "6E", "country": "Mexico" },
  { "prefix": "6F", "country": "Mexico" },
  { "prefix": "6G", "country": "Mexico" },
  { "prefix": "6H", "country": "Mexico" },
  { "prefix": "6I", "country": "Mexico" },
  { "prefix": "6J", "country": "Mexico" },
  { "prefix": "6K", "country": "South Korea" },
  { "prefix": "6L", "country": "South Korea" },
  { "prefix": "6M", "country": "South Korea" },
  { "prefix": "6N", "country": "South Korea" },
  { "prefix": "6O", "country": "Somalia" },
  { "prefix": "6P", "country": "Pakistan" },
  { "prefix": "6Q", "country": "Pakistan" },
  { "prefix": "6R", "country": "Pakistan" },
  { "prefix": "6S", "country": "Pakistan" },
  { "prefix": "6T", "country": "Sudan" },
  { "prefix": "6U", "country": "Sudan" },
  { "prefix": "6V", "country": "Senegal" },
  { "prefix": "6W", "country": "Senegal" },
  { "prefix": "6X", "country": "Madagascar" },
  { "prefix": "6Y", "country": "Jamaica" },
  { "prefix": "6Z", "country": "Liberia" },
  { "prefix": "7A", "country": "Indonesia" },
  { "prefix": "7B", "country": "Indonesia" },
  { "prefix": "7C", "country": "Indonesia" },
  { "prefix": "7D", "country": "Indonesia" },
  { "prefix": "7E", "country": "Indonesia" },
  { "prefix": "7F", "country": "Indonesia" },
  { "prefix": "7G", "country": "Indonesia" },
  { "prefix": "7H", "country": "Indonesia" },
  { "prefix": "7I", "country": "Indonesia" },
  { "prefix": "7J", "country": "Japan" },
  { "prefix": "7K", "country": "Japan" },
  { "prefix": "7L", "country": "Japan" },
  { "prefix": "7M", "country": "Japan" },
  { "prefix": "7N", "country": "Japan" },
  { "prefix": "7O", "country": "Yemen" },
  { "prefix": "7P", "country": "Lesotho" },
  { "prefix": "7Q", "country": "Malawi" },
  { "prefix": "7R", "country": "Algeria" },
  { "prefix": "7S", "country": "Sweden" },
  { "prefix": "7T", "country": "Algeria" },
  { "prefix": "7U", "country": "Algeria" },
  { "prefix": "7V", "country": "Algeria" },
  { "prefix": "7W", "country": "Algeria" },
  { "prefix": "7X", "country": "Algeria" },
  { "prefix": "7Y", "country": "Algeria" },
  { "prefix": "7Z", "country": "Saudi Arabia" },
  { "prefix": "8A", "country": "Indonesia" },
  { "prefix": "8B", "country": "Indonesia" },
  { "prefix": "8C", "country": "Indonesia" },
  { "prefix": "8D", "country": "Indonesia" },
  { "prefix": "8E", "country": "Indonesia" },
  { "prefix": "8F", "country": "Indonesia" },
  { "prefix": "8G", "country": "Indonesia" },
  { "prefix": "8H", "country": "Indonesia" },
  { "prefix": "8I", "country": "Indonesia" },
  { "prefix": "8J", "country": "Japan" },
  { "prefix": "8K", "country": "Japan" },
  { "prefix": "8L", "country": "Japan" },
  { "prefix": "8M", "country": "Japan" },
  { "prefix": "8N", "country": "Japan" },
  { "prefix": "8O", "country": "Botswana" },
  { "prefix": "8P", "country": "Barbados" },
  { "prefix": "8Q", "country": "Maldives" },
  { "prefix": "8R", "country": "Guyana" },
  { "prefix": "8S", "country": "Sweden" },
  { "prefix": "8T", "country": "India" },
  { "prefix": "8U", "country": "India" },
  { "prefix": "8V", "country": "India" },
  { "prefix": "8W", "country": "India" },
  { "prefix": "8X", "country": "India" },
  { "prefix": "8Y", "country": "India" },
  { "prefix": "8Z", "country": "Saudi Arabia" },
  { "prefix": "9A", "country": "Croatia" },
  { "prefix": "9B", "country": "Iran" },
  { "prefix": "9C", "country": "Iran" },
  { "prefix": "9D", "country": "Iran" },
  { "prefix": "9E", "country": "Ethiopia" },
  { "prefix": "9F", "country": "Ethiopia" },
  { "prefix": "9G", "country": "Ghana" },
  { "prefix": "9H", "country": "Malta" },
  { "prefix": "9I", "country": "Zambia" },
  { "prefix": "9J", "country": "Zambia" },
  { "prefix": "9K", "country": "Kuwait" },
  { "prefix": "9L", "country": "Sierra Leone" },
  { "prefix": "9M", "country": "Malaysia" },
  { "prefix": "9N", "country": "Nepal" },
  { "prefix": "9O", "country": "Democratic Republic of the Congo" },
  { "prefix": "9P", "country": "Democratic Republic of the Congo" },
  { "prefix": "9Q", "country": "Democratic Republic of the Congo" },
  { "prefix": "9R", "country": "Democratic Republic of the Congo" },
  { "prefix": "9S", "country": "Democratic Republic of the Congo" },
  { "prefix": "9T", "country": "Democratic Republic of the Congo" },
  { "prefix": "9U", "country": "Burundi" },
  { "prefix": "9V", "country": "Singapore" },
  { "prefix": "9W", "country": "Malaysia" },
  { "prefix": "9X", "country": "Rwanda" },
  { "prefix": "9Y", "country": "Trinidad and Tobago" },
  { "prefix": "9Z", "country": "Trinidad and Tobago" },
  { "prefix": "A2", "country": "Botswana" },
  { "prefix": "A3", "country": "Tonga" },
  { "prefix": "A4", "country": "Oman" },
  { "prefix": "A5", "country": "Bhutan" },
  { "prefix": "A6", "country": "United Arab Emirates" },
  { "prefix": "A7", "country": "Qatar" },
  { "prefix": "A8", "country": "Liberia" },
  { "prefix": "A9", "country": "Bahrain" },
  { "prefix": "AA", "country": "United States of America" },
  { "prefix": "AB", "country": "United States of America" },
  { "prefix": "AC", "country": "United States of America" },
  { "prefix": "AD", "country": "United States of America" },
  { "prefix": "AE", "country": "United States of America" },
  { "prefix": "AF", "country": "United States of America" },
  { "prefix": "AG", "country": "United States of America" },
  { "prefix": "AH", "country": "United States of America" },
  { "prefix": "AI", "country": "United States of America" },
  { "prefix": "AJ", "country": "United States of America" },
  { "prefix": "AK", "country": "United States of America" },
  { "prefix": "AL", "country": "United States of America" },
  { "prefix": "AM", "country": "Spain" },
  { "prefix": "AN", "country": "Spain" },
  { "prefix": "AO", "country": "Spain" },
  { "prefix": "AP", "country": "Pakistan" },
  { "prefix": "AR", "country": "Pakistan" },
  { "prefix": "AS", "country": "Pakistan" },
  { "prefix": "AT", "country": "India" },
  { "prefix": "AU", "country": "India" },
  { "prefix": "AV", "country": "India" },
  { "prefix": "AW", "country": "India" },
  { "prefix": "AX", "country": "Australia" },
  { "prefix": "AY", "country": "Argentina" },
  { "prefix": "AZ", "country": "Argentina" },
  { "prefix": "B", "country": "China" },
  { "prefix": "C2", "country": "Nauru" },
  { "prefix": "C3", "country": "Andorra" },
  { "prefix": "C4", "country": "Cyprus" },
  { "prefix": "C5", "country": "Gambia" },
  { "prefix": "C6", "country": "Bahamas" },
  { "prefix": "C7", "country": "World Meteorological Organization (Non-geographical)" },
  { "prefix": "C8", "country": "Mozambique" },
  { "prefix": "C9", "country": "Mozambique" },
  { "prefix": "CA", "country": "Chile" },
  { "prefix": "CB", "country": "Chile" },
  { "prefix": "CC", "country": "Chile" },
  { "prefix": "CD", "country": "Chile" },
  { "prefix": "CE", "country": "Chile" },
  { "prefix": "CF", "country": "Canada" },
  { "prefix": "CG", "country": "Canada" },
  { "prefix": "CH", "country": "Canada" },
  { "prefix": "CI", "country": "Canada" },
  { "prefix": "CJ", "country": "Canada" },
  { "prefix": "CK", "country": "Canada" },
  { "prefix": "CL", "country": "Cuba" },
  { "prefix": "CM", "country": "Cuba" },
  { "prefix": "CN", "country": "Morocco" },
  { "prefix": "CO", "country": "Cuba" },
  { "prefix": "CP", "country": "Bolivia" },
  { "prefix": "CQ", "country": "Portugal" },
  { "prefix": "CR", "country": "Portugal" },
  { "prefix": "CS", "country": "Portugal" },
  { "prefix": "CT", "country": "Portugal" },
  { "prefix": "CU", "country": "Portugal" },
  { "prefix": "CV", "country": "Uruguay" },
  { "prefix": "CW", "country": "Uruguay" },
  { "prefix": "CX", "country": "Uruguay" },
  { "prefix": "CY", "country": "Canada" },
  { "prefix": "CZ", "country": "Canada" },
  { "prefix": "D2", "country": "Angola" },
  { "prefix": "D3", "country": "Angola" },
  { "prefix": "D4", "country": "Cape Verde" },
  { "prefix": "D5", "country": "Liberia" },
  { "prefix": "D6", "country": "Comoros" },
  { "prefix": "D7", "country": "South Korea" },
  { "prefix": "D8", "country": "South Korea" },
  { "prefix": "D9", "country": "South Korea" },
  { "prefix": "DA", "country": "Germany" },
  { "prefix": "DB", "country": "Germany" },
  { "prefix": "DC", "country": "Germany" },
  { "prefix": "DD", "country": "Germany" },
  { "prefix": "DE", "country": "Germany" },
  { "prefix": "DF", "country": "Germany" },
  { "prefix": "DG", "country": "Germany" },
  { "prefix": "DH", "country": "Germany" },
  { "prefix": "DI", "country": "Germany" },
  { "prefix": "DJ", "country": "Germany" },
  { "prefix": "DK", "country": "Germany" },
  { "prefix": "DL", "country": "Germany" },
  { "prefix": "DM", "country": "Germany" },
  { "prefix": "DN", "country": "Germany" },
  { "prefix": "DO", "country": "Germany" },
  { "prefix": "DP", "country": "Germany" },
  { "prefix": "DQ", "country": "Germany" },
  { "prefix": "DR", "country": "Germany" },
  { "prefix": "DS", "country": "South Korea" },
  { "prefix": "DT", "country": "South Korea" },
  { "prefix": "DU", "country": "Philippines" },
  { "prefix": "DV", "country": "Philippines" },
  { "prefix": "DW", "country": "Philippines" },
  { "prefix": "DX", "country": "Philippines" },
  { "prefix": "DY", "country": "Philippines" },
  { "prefix": "DZ", "country": "Philippines" },
  { "prefix": "E2", "country": "Thailand" },
  { "prefix": "E3", "country": "Eritrea" },
  { "prefix": "E4", "country": "Palestinian Authority" },
  { "prefix": "E5", "country": "New Zealand (Cook Islands)" },
  { "prefix": "E6", "country": "New Zealand (Niue)" },
  { "prefix": "E7", "country": "Bosnia and Herzegovina" },
  { "prefix": "EA", "country": "Spain" },
  { "prefix": "EB", "country": "Spain" },
  { "prefix": "EC", "country": "Spain" },
  { "prefix": "ED", "country": "Spain" },
  { "prefix": "EE", "country": "Spain" },
  { "prefix": "EF", "country": "Spain" },
  { "prefix": "EG", "country": "Spain" },
  { "prefix": "EH", "country": "Spain" },
  { "prefix": "EI", "country": "Ireland" },
  { "prefix": "EJ", "country": "Ireland" },
  { "prefix": "EK", "country": "Armenia" },
  { "prefix": "EL", "country": "Liberia" },
  { "prefix": "EM", "country": "Ukraine" },
  { "prefix": "EN", "country": "Ukraine" },
  { "prefix": "EO", "country": "Ukraine" },
  { "prefix": "EP", "country": "Iran" },
  { "prefix": "EQ", "country": "Iran" },
  { "prefix": "ER", "country": "Moldova" },
  { "prefix": "ES", "country": "Estonia" },
  { "prefix": "ET", "country": "Ethiopia" },
  { "prefix": "EU", "country": "Belarus" },
  { "prefix": "EV", "country": "Belarus" },
  { "prefix": "EW", "country": "Belarus" },
  { "prefix": "EX", "country": "Kyrgyz Republic" },
  { "prefix": "EY", "country": "Tajikistan" },
  { "prefix": "EZ", "country": "Turkmenistan" },
  { "prefix": "F", "country": "France" },
  { "prefix": "G", "country": "United Kingdom" },
  { "prefix": "HA", "country": "Hungary" },
  { "prefix": "HB", "country": "Switzerland" },
  { "prefix": "HC", "country": "Ecuador" },
  { "prefix": "HD", "country": "Ecuador" },
  { "prefix": "HE", "country": "Switzerland" },
  { "prefix": "HF", "country": "Poland" },
  { "prefix": "HG", "country": "Hungary" },
  { "prefix": "HH", "country": "Haiti" },
  { "prefix": "HI", "country": "Dominican Republic" },
  { "prefix": "HJ", "country": "Colombia" },
  { "prefix": "HK", "country": "Colombia" },
  { "prefix": "HL", "country": "South Korea" },
  { "prefix": "HM", "country": "North Korea" },
  { "prefix": "HN", "country": "Iraq" },
  { "prefix": "HO", "country": "Panama" },
  { "prefix": "HP", "country": "Panama" },
  { "prefix": "HQ", "country": "Honduras" },
  { "prefix": "HR", "country": "Honduras" },
  { "prefix": "HS", "country": "Thailand" },
  { "prefix": "HT", "country": "Nicaragua" },
  { "prefix": "HU", "country": "El Salvador" },
  { "prefix": "HV", "country": "Vatican City State" },
  { "prefix": "HW", "country": "France" },
  { "prefix": "HX", "country": "France" },
  { "prefix": "HY", "country": "France" },
  { "prefix": "HZ", "country": "Saudi Arabia" },
  { "prefix": "I", "country": "Italy" },
  { "prefix": "J2", "country": "Djibouti" },
  { "prefix": "J3", "country": "Grenada" },
  { "prefix": "J4", "country": "Greece" },
  { "prefix": "J5", "country": "Guinea-Bissau" },
  { "prefix": "J6", "country": "Saint Lucia" },
  { "prefix": "J7", "country": "Dominica" },
  { "prefix": "J8", "country": "Saint Vincent and the Grenadines" },
  { "prefix": "JA", "country": "Japan" },
  { "prefix": "JB", "country": "Japan" },
  { "prefix": "JC", "country": "Japan" },
  { "prefix": "JD", "country": "Japan" },
  { "prefix": "JE", "country": "Japan" },
  { "prefix": "JF", "country": "Japan" },
  { "prefix": "JG", "country": "Japan" },
  { "prefix": "JH", "country": "Japan" },
  { "prefix": "JI", "country": "Japan" },
  { "prefix": "JJ", "country": "Japan" },
  { "prefix": "JK", "country": "Japan" },
  { "prefix": "JL", "country": "Japan" },
  { "prefix": "JM", "country": "Japan" },
  { "prefix": "JN", "country": "Japan" },
  { "prefix": "JO", "country": "Japan" },
  { "prefix": "JP", "country": "Japan" },
  { "prefix": "JQ", "country": "Japan" },
  { "prefix": "JR", "country": "Japan" },
  { "prefix": "JS", "country": "Japan" },
  { "prefix": "JT", "country": "Mongolia" },
  { "prefix": "JU", "country": "Mongolia" },
  { "prefix": "JV", "country": "Mongolia" },
  { "prefix": "JW", "country": "Norway" },
  { "prefix": "JX", "country": "Norway" },
  { "prefix": "JY", "country": "Jordan" },
  { "prefix": "JZ", "country": "Indonesia" },
  { "prefix": "K", "country": "United States of America" },
  { "prefix": "LA", "country": "Norway" },
  { "prefix": "LB", "country": "Norway" },
  { "prefix": "LC", "country": "Norway" },
  { "prefix": "LD", "country": "Norway" },
  { "prefix": "LE", "country": "Norway" },
  { "prefix": "LF", "country": "Norway" },
  { "prefix": "LG", "country": "Norway" },
  { "prefix": "LH", "country": "Norway" },
  { "prefix": "LI", "country": "Norway" },
  { "prefix": "LJ", "country": "Norway" },
  { "prefix": "LK", "country": "Norway" },
  { "prefix": "LL", "country": "Norway" },
  { "prefix": "LM", "country": "Norway" },
  { "prefix": "LN", "country": "Norway" },
  { "prefix": "LO", "country": "Argentina" },
  { "prefix": "LP", "country": "Argentina" },
  { "prefix": "LQ", "country": "Argentina" },
  { "prefix": "LR", "country": "Argentina" },
  { "prefix": "LS", "country": "Argentina" },
  { "prefix": "LT", "country": "Argentina" },
  { "prefix": "LU", "country": "Argentina" },
  { "prefix": "LV", "country": "Argentina" },
  { "prefix": "LW", "country": "Argentina" },
  { "prefix": "LX", "country": "Luxembourg" },
  { "prefix": "LY", "country": "Lithuania" },
  { "prefix": "LZ", "country": "Bulgaria" },
  { "prefix": "M", "country": "United Kingdom" },
  { "prefix": "N", "country": "United States of America" },
  { "prefix": "OA", "country": "Peru" },
  { "prefix": "OB", "country": "Peru" },
  { "prefix": "OC", "country": "Peru" },
  { "prefix": "OD", "country": "Lebanon" },
  { "prefix": "OE", "country": "Austria" },
  { "prefix": "OF", "country": "Finland" },
  { "prefix": "OG", "country": "Finland" },
  { "prefix": "OH", "country": "Finland" },
  { "prefix": "OI", "country": "Finland" },
  { "prefix": "OJ", "country": "Finland" },
  { "prefix": "OK", "country": "Czech Republic" },
  { "prefix": "OL", "country": "Czech Republic" },
  { "prefix": "OM", "country": "Slovak Republic" },
  { "prefix": "ON", "country": "Belgium" },
  { "prefix": "OO", "country": "Belgium" },
  { "prefix": "OP", "country": "Belgium" },
  { "prefix": "OQ", "country": "Belgium" },
  { "prefix": "OR", "country": "Belgium" },
  { "prefix": "OS", "country": "Belgium" },
  { "prefix": "OT", "country": "Belgium" },
  { "prefix": "OU", "country": "Denmark" },
  { "prefix": "OV", "country": "Denmark" },
  { "prefix": "OW", "country": "Denmark" },
  { "prefix": "OX", "country": "Denmark (Greenland)" },
  { "prefix": "OY", "country": "Denmark (Faroe Islands)" },
  { "prefix": "OZ", "country": "Denmark" },
  { "prefix": "P2", "country": "Papua New Guinea" },
  { "prefix": "P3", "country": "Cyprus" },
  { "prefix": "P4", "country": "Aruba" },
  { "prefix": "P5", "country": "North Korea" },
  { "prefix": "P6", "country": "North Korea" },
  { "prefix": "P7", "country": "North Korea" },
  { "prefix": "P8", "country": "North Korea" },
  { "prefix": "P9", "country": "North Korea" },
  { "prefix": "PA", "country": "Netherlands" },
  { "prefix": "PB", "country": "Netherlands" },
  { "prefix": "PC", "country": "Netherlands" },
  { "prefix": "PD", "country": "Netherlands" },
  { "prefix": "PE", "country": "Netherlands" },
  { "prefix": "PF", "country": "Netherlands" },
  { "prefix": "PG", "country": "Netherlands" },
  { "prefix": "PH", "country": "Netherlands" },
  { "prefix": "PI", "country": "Netherlands" },
  { "prefix": "PJ", "country": "Netherlands Antilles" },
  { "prefix": "PK", "country": "Indonesia" },
  { "prefix": "PL", "country": "Indonesia" },
  { "prefix": "PM", "country": "Indonesia" },
  { "prefix": "PN", "country": "Indonesia" },
  { "prefix": "PO", "country": "Indonesia" },
  { "prefix": "PP", "country": "Brazil" },
  { "prefix": "PQ", "country": "Brazil" },
  { "prefix": "PR", "country": "Brazil" },
  { "prefix": "PS", "country": "Brazil" },
  { "prefix": "PT", "country": "Brazil" },
  { "prefix": "PU", "country": "Brazil" },
  { "prefix": "PV", "country": "Brazil" },
  { "prefix": "PW", "country": "Brazil" },
  { "prefix": "PX", "country": "Brazil" },
  { "prefix": "PY", "country": "Brazil" },
  { "prefix": "PZ", "country": "Suriname" },
  { "prefix": "R", "country": "Russian Federation" },
  { "prefix": "S2", "country": "Bangladesh" },
  { "prefix": "S3", "country": "Bangladesh" },
  { "prefix": "S5", "country": "Slovenia" },
  { "prefix": "S6", "country": "Singapore" },
  { "prefix": "S7", "country": "Seychelles" },
  { "prefix": "S8", "country": "South Africa" },
  { "prefix": "S9", "country": "Sao Tome and Principe" },
  { "prefix": "SA", "country": "Sweden" },
  { "prefix": "SB", "country": "Sweden" },
  { "prefix": "SC", "country": "Sweden" },
  { "prefix": "SD", "country": "Sweden" },
  { "prefix": "SE", "country": "Sweden" },
  { "prefix": "SF", "country": "Sweden" },
  { "prefix": "SG", "country": "Sweden" },
  { "prefix": "SH", "country": "Sweden" },
  { "prefix": "SI", "country": "Sweden" },
  { "prefix": "SJ", "country": "Sweden" },
  { "prefix": "SK", "country": "Sweden" },
  { "prefix": "SL", "country": "Sweden" },
  { "prefix": "SM", "country": "Sweden" },
  { "prefix": "SN", "country": "Poland" },
  { "prefix": "SO", "country": "Poland" },
  { "prefix": "SP", "country": "Poland" },
  { "prefix": "SQ", "country": "Poland" },
  { "prefix": "SR", "country": "Poland" },
  { "prefix": "SS", "country": "Egypt" },
  { "prefix": "ST", "country": "Sudan" },
  { "prefix": "SU", "country": "Egypt" },
  { "prefix": "SV", "country": "Greece" },
  { "prefix": "SW", "country": "Greece" },
  { "prefix": "SX", "country": "Greece" },
  { "prefix": "SY", "country": "Greece" },
  { "prefix": "SZ", "country": "Greece" },
  { "prefix": "T2", "country": "Tuvalu" },
  { "prefix": "T3", "country": "Kiribati" },
  { "prefix": "T4", "country": "Cuba" },
  { "prefix": "T5", "country": "Somalia" },
  { "prefix": "T6", "country": "Afghanistan" },
  { "prefix": "T7", "country": "San Marino" },
  { "prefix": "T8", "country": "Palau" },
  { "prefix": "TA", "country": "Turkey" },
  { "prefix": "TB", "country": "Turkey" },
  { "prefix": "TC", "country": "Turkey" },
  { "prefix": "TD", "country": "Guatemala" },
  { "prefix": "TE", "country": "Costa Rica" },
  { "prefix": "TF", "country": "Iceland" },
  { "prefix": "TG", "country": "Guatemala" },
  { "prefix": "TH", "country": "France" },
  { "prefix": "TI", "country": "Costa Rica" },
  { "prefix": "TJ", "country": "Cameroon" },
  { "prefix": "TK", "country": "France" },
  { "prefix": "TL", "country": "Central African Republic" },
  { "prefix": "TM", "country": "France" },
  { "prefix": "TN", "country": "Congo (Republic of the)" },
  { "prefix": "TO", "country": "France" },
  { "prefix": "TP", "country": "France" },
  { "prefix": "TQ", "country": "France" },
  { "prefix": "TR", "country": "Gabon" },
  { "prefix": "TT", "country": "Chad" },
  { "prefix": "TU", "country": "Côte d'Ivoire" },
  { "prefix": "TV", "country": "France" },
  { "prefix": "TW", "country": "France" },
  { "prefix": "TX", "country": "France" },
  { "prefix": "TY", "country": "Benin" },
  { "prefix": "TZ", "country": "Mali" },
  { "prefix": "UA", "country": "Russian Federation" },
  { "prefix": "UB", "country": "Russian Federation" },
  { "prefix": "UC", "country": "Russian Federation" },
  { "prefix": "UD", "country": "Russian Federation" },
  { "prefix": "UE", "country": "Russian Federation" },
  { "prefix": "UF", "country": "Russian Federation" },
  { "prefix": "UG", "country": "Russian Federation" },
  { "prefix": "UH", "country": "Russian Federation" },
  { "prefix": "UI", "country": "Russian Federation" },
  { "prefix": "UJ", "country": "Uzbekistan" },
  { "prefix": "UK", "country": "Uzbekistan" },
  { "prefix": "UL", "country": "Uzbekistan" },
  { "prefix": "UM", "country": "Uzbekistan" },
  { "prefix": "UN", "country": "Kazakhstan" },
  { "prefix": "UO", "country": "Kazakhstan" },
  { "prefix": "UP", "country": "Kazakhstan" },
  { "prefix": "UQ", "country": "Kazakhstan" },
  { "prefix": "UR", "country": "Ukraine" },
  { "prefix": "US", "country": "Ukraine" },
  { "prefix": "UT", "country": "Ukraine" },
  { "prefix": "UU", "country": "Ukraine" },
  { "prefix": "UV", "country": "Ukraine" },
  { "prefix": "UW", "country": "Ukraine" },
  { "prefix": "UX", "country": "Ukraine" },
  { "prefix": "UY", "country": "Ukraine" },
  { "prefix": "UZ", "country": "Ukraine" },
  { "prefix": "V2", "country": "Antigua and Barbuda" },
  { "prefix": "V3", "country": "Belize" },
  { "prefix": "V4", "country": "Saint Kitts and Nevis" },
  { "prefix": "V5", "country": "Namibia" },
  { "prefix": "V6", "country": "Micronesia" },
  { "prefix": "V7", "country": "Marshall Islands" },
  { "prefix": "V8", "country": "Brunei Darussalam" },
  { "prefix": "VA", "country": "Canada" },
  { "prefix": "VB", "country": "Canada" },
  { "prefix": "VC", "country": "Canada" },
  { "prefix": "VD", "country": "Canada" },
  { "prefix": "VE", "country": "Canada" },
  { "prefix": "VF", "country": "Canada" },
  { "prefix": "VG", "country": "Canada" },
  { "prefix": "VH", "country": "Australia" },
  { "prefix": "VI", "country": "Australia" },
  { "prefix": "VJ", "country": "Australia" },
  { "prefix": "VK", "country": "Australia" },
  { "prefix": "VL", "country": "Australia" },
  { "prefix": "VM", "country": "Australia" },
  { "prefix": "VN", "country": "Australia" },
  { "prefix": "VO", "country": "Canada" },
  { "prefix": "VP", "country": "United Kingdom (Overseas Territories)" },
  { "prefix": "VQ", "country": "United Kingdom (Overseas Territories)" },
  { "prefix": "VR", "country": "China (Hong Kong)" },
  { "prefix": "VS", "country": "United Kingdom (Overseas Territories)" },
  { "prefix": "VT", "country": "India" },
  { "prefix": "VU", "country": "India" },
  { "prefix": "VV", "country": "India" },
  { "prefix": "VW", "country": "India" },
  { "prefix": "VX", "country": "Canada" },
  { "prefix": "VY", "country": "Canada" },
  { "prefix": "VZ", "country": "Australia" },
  { "prefix": "W", "country": "United States of America" },
  { "prefix": "XA", "country": "Mexico" },
  { "prefix": "XB", "country": "Mexico" },
  { "prefix": "XC", "country": "Mexico" },
  { "prefix": "XD", "country": "Mexico" },
  { "prefix": "XE", "country": "Mexico" },
  { "prefix": "XF", "country": "Mexico" },
  { "prefix": "XG", "country": "Mexico" },
  { "prefix": "XH", "country": "Mexico" },
  { "prefix": "XI", "country": "Mexico" },
  { "prefix": "XU", "country": "Cambodia" },
  { "prefix": "XV", "country": "Vietnam" },
  { "prefix": "XW", "country": "Laos" },
  { "prefix": "XX", "country": "China (Macao)" },
  { "prefix": "XY", "country": "Myanmar" },
  { "prefix": "XZ", "country": "Myanmar" },
  { "prefix": "Y2", "country": "Germany" },
  { "prefix": "Y3", "country": "Germany" },
  { "prefix": "Y4", "country": "Germany" },
  { "prefix": "Y5", "country": "Germany" },
  { "prefix": "Y6", "country": "Germany" },
  { "prefix": "Y7", "country": "Germany" },
  { "prefix": "Y8", "country": "Germany" },
  { "prefix": "Y9", "country": "Germany" },
  { "prefix": "YA", "country": "Afghanistan" },
  { "prefix": "YB", "country": "Indonesia" },
  { "prefix": "YC", "country": "Indonesia" },
  { "prefix": "YD", "country": "Indonesia" },
  { "prefix": "YE", "country": "Indonesia" },
  { "prefix": "YF", "country": "Indonesia" },
  { "prefix": "YG", "country": "Indonesia" },
  { "prefix": "YH", "country": "Indonesia" },
  { "prefix": "YI", "country": "Iraq" },
  { "prefix": "YJ", "country": "Vanuatu" },
  { "prefix": "YK", "country": "Syria" },
  { "prefix": "YL", "country": "Latvia" },
  { "prefix": "YM", "country": "Turkey" },
  { "prefix": "YN", "country": "Nicaragua" },
  { "prefix": "YO", "country": "Romania" },
  { "prefix": "YP", "country": "Romania" },
  { "prefix": "YQ", "country": "Romania" },
  { "prefix": "YR", "country": "Romania" },
  { "prefix": "YS", "country": "El Salvador" },
  { "prefix": "YT", "country": "Serbia" },
  { "prefix": "YU", "country": "Serbia" },
  { "prefix": "YV", "country": "Venezuela" },
  { "prefix": "YW", "country": "Venezuela" },
  { "prefix": "YX", "country": "Venezuela" },
  { "prefix": "YY", "country": "Venezuela" },
  { "prefix": "Z2", "country": "Zimbabwe" },
  { "prefix": "Z3", "country": "North Macedonia" },
  { "prefix": "ZA", "country": "Albania" },
  { "prefix": "ZB", "country": "United Kingdom (Overseas Territories)" },
  { "prefix": "ZC", "country": "United Kingdom (Overseas Territories)" },
  { "prefix": "ZD", "country": "United Kingdom (Overseas Territories)" },
  { "prefix": "ZE", "country": "United Kingdom (Overseas Territories)" },
  { "prefix": "ZF", "country": "United Kingdom (Overseas Territories)" },
  { "prefix": "ZG", "country": "United Kingdom (Overseas Territories)" },
  { "prefix": "ZH", "country": "United Kingdom (Overseas Territories)" },
  { "prefix": "ZI", "country": "United Kingdom (Overseas Territories)" },
  { "prefix": "ZJ", "country": "United Kingdom (Overseas Territories)" },
  { "prefix": "ZK", "country": "New Zealand" },
  { "prefix": "ZL", "country": "New Zealand" },
  { "prefix": "ZM", "country": "New Zealand" },
  { "prefix": "ZN", "country": "United Kingdom (Overseas Territories)" },
  { "prefix": "ZO", "country": "United Kingdom (Overseas Territories)" },
  { "prefix": "ZP", "country": "Paraguay" },
  { "prefix": "ZQ", "country": "United Kingdom (Overseas Territories)" },
  { "prefix": "ZR", "country": "South Africa" },
  { "prefix": "ZS", "country": "South Africa" },
  { "prefix": "ZT", "country": "South Africa" },
  { "prefix": "ZU", "country": "South Africa" },
  { "prefix": "ZV", "country": "Brazil" },
  { "prefix": "ZW", "country": "Brazil" },
  { "prefix": "ZX", "country": "Brazil" },
  { "prefix": "ZY", "country": "Brazil" },
  { "prefix": "ZZ", "country": "Brazil" }
].sort((a, b) => b.prefix.length - a.prefix.length);